### ISSUE TITLE
Implement google map on Location Service

### ISSUE THREAD

**Issue by purnama** [purnama/hackmdk3#16]
Google map location on the right site of the location choosed.

**Comment by purnama** [comment]
Here is a sample how to put the marker
https://angular-ui.github.io/angular-google-maps/#!/api/marker

A marker has been put as an example for PTSP Cengkareng Timur

Here is how to get the Longitude & latitude from Google Maps
https://support.google.com/maps/answer/18539?hl=en
See "Get the coordinates of a place"

**Comment by sastrandi** [comment]
ok thur. danke yah, gw lanjutin task nya.

**Comment by sastrandi** [comment]
done
